categories:
- Climate Analysis
description: EMERALD version of the Functionally Assembled Terrestrial Ecosystem Simulator (FATES) with Community Terrestrial Systems Model as host model
homepage_url: https://github.com/NordicESMhub/ctsm/blob/fates_emerald_api/README_fates_emerald_api
long_description: |
  This tool is a wrapper for the Functionally Assembled Terrestrial Ecosystem Simulator (FATES) for Nordic sites. All the available sites are listed at https://github.com/NordicESMhub/ctsm/blob/fates_emerald_api/README_fates_emerald_api. It allows the creation of a new case (startup), or a hybrid run where restart files will have to be specified too. The simulation can be customized by the most common options.
name: ctsm_fates
owner: climate
remote_repository_url: https://github.com/NordicESMhub/galaxy-tools/tree/master/tools/fates-emerald
type: unrestricted
