#!/bin/bash
# Anne Fouilloux
# University of Oslo, Norway
# 2015

WRFversion=$1
wrf_type=$2
debug=$3
io_type=$4
WRFexp=$5
outputdir=$6
ofilename=$7
if [ "$#" -ge 8 ]; then
  tblfile=$8
else
  tblfile=""
fi

echo "WRF version    : $WRFversion"
echo "WRFexp         : $WRFexp"
echo "WRF type       : $wrf_type"
echo "WRF debug level: $debug"
echo "output dir     : $outputdir"
echo "output file    : $ofilename"
echo "GEOGRID.TBL    : $tblfile"

export RUNDIR=$outputdir
export WRF_EXPID=`grep WRF_EXPID $WRFexp | awk -F= '{print $2}'`
geog_data_path=`grep -i geog_data_path $WRFexp | awk -F= '{print $2}'`

generateWPSnamelist.py --wrfexp $WRFexp --debug $debug --io_form_grid $io_type -o $outputdir/namelist.wps 

if [ "$tblfile" == "" ] ; then
# take default GEOGRID.TBL file
   generateGeogridTBL.py --type $wrf_type -o $outputdir/GEOGRID.TBL
   tblfile=$outputdir/GEOGRID.TBL 
else
   echo "User-defined GEOGRID.TBL is $tblfile"
fi

echo "calling geogrid.exe... $outputdir/$WRF_EXPID"
if [ "$geog_data_path" == "" ] ; then
  echo "WPS geog path: $WPS_GEOG_PATH"
  run_geogrid.py -p $outputdir --expid $WRF_EXPID --wps_geog $WPS_GEOG_PATH --tbl $tblfile
else
  echo "WPS geog path: $geog_data_path"
  run_geogrid.py -p $outputdir --expid $WRF_EXPID --wps_geog $geog_data_path --tbl $tblfile
fi

mv $outputdir/$WRF_EXPID/* $outputdir/.
rm -rf $outputdir/$WRF_EXPID


# list all created files
cat  >> header.html  << EOF
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <title><h1><b>WPS/WRF geogrid dataset generated by running geogrid.exe</b></h1></title>

   <p><font size="4" style="font-size: 14pt"><i>expid: $WRF_EXPID</i></font></p>
   <p><font size="4" style="font-size: 14pt"><i>version: $WRFversion</i></font></p>
   <p><font size="4" style="font-size: 14pt"><i>WRF_KPP: $WRF_KPP</i></font></p>
   <p><font size="4" style="font-size: 14pt"><i>geo_em.dXX.nc files are netCDF files generated for each domain (d01 for domain 1, etc.).</i></font></p>
   <p><br></br></p>
   <h2>Logs</h2>
   <ul>
   <li><a href="${WRF_EXPID}.wrfexp">${WRF_EXPID}.wrfexp</a>  <a href="[download]${WRF_EXPID}.wrfexp">[download]</a></li>
   </ul>
   <p><br></br></p>
</head>
EOF


current_pwd=`pwd`
cd $outputdir
html_wrflistfiles.py --inputdir=./ --html=$ofilename --header=$current_pwd/header.html

rm -rf $current_pwd/header.html
# copy setup file in working directory
cp $WRFexp $outputdir/${WRF_EXPID}.wrfexp
