#!/bin/bash
# Anne Fouilloux
# University of Oslo, Norway
# 2015

WRFversion=$1
wrf_type=$2
WRFexp=$3
script_file=$4
outputdir=$5
ofilename=$6
if [ "$#" -ge 7 ]; then
  tblfile=$7
else
  tblfile=""
fi

echo "WRF version    : $WRFversion"
echo "WRFexp         : $WRFexp"
echo "WRF type       : $wrf_type"
echo "script_file    : $script_file"
echo "output dir     : $outputdir"
echo "output file    : $ofilename"
echo "METGRID        : $tblfile"

export RUNDIR=$outputdir

export WRF_EXPID=`grep WRF_EXPID $WRFexp | awk -F= '{print $2}'`

echo "WRF_EXPID = $WRF_EXPID"

mkdir -p $outputdir/$WRF_EXPID

generateMETGRIDnamelist.py --expid $WRF_EXPID --metgrid $script_file -o $outputdir/$WRF_EXPID/namelist.wps 

echo "=============================================="
cat $outputdir/$WRF_EXPID/namelist.wps
echo "=============================================="

if [ "$tblfile" == "" ] ; then
# take default METGRID.TBL file
   generateMETGRIDTBL.py --type $wrf_type -o $outputdir/METGRID.TBL
   tblfile=$outputdir/METGRID.TBL 
else
   echo "User-defined METGRID.TBL is $tblfile"
fi

# Make sure all the datasets are available to metgrid.exe (i.e. located in $outputdir/$WRF_EXPID)
echo "calling metgrid.exe... $outputdir/$WRF_EXPID"
run_metgrid.py --expid $WRF_EXPID --tbl $tblfile --version $WRFversion


current_pwd=`pwd`
cd $outputdir/$WRF_EXPID

# Remove symbolic links and metgrid directory
find -type l -exec rm {} \;
rm -rf metgrid

cd $current_pwd

# list all created files
cat  >> header.html  << EOF
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <title><h1><b>WPS/WRF metgrid dataset generated by running metgrid.exe</b></h1></title>

   <p><font size="4" style="font-size: 14pt"><i>expid: $WRF_EXPID</i></font></p>
   <p><font size="4" style="font-size: 14pt"><i>version: $WRFversion</i></font></p>
   <p><font size="4" style="font-size: 14pt"><i>WRF_KPP: $WRF_KPP</i></font></p>
   <p><br></br></p>
   <h2>Logs</h2>
   <ul>
   <li><a href="${WRF_EXPID}.wrfexp">${WRF_EXPID}.wrfexp</a>  <a href="[download]${WRF_EXPID}.wrfexp">[download]</a></li>
   </ul>
   <p><br></br></p>
</head>
EOF


cd $outputdir
html_wrflistfiles.py --inputdir=./ --html=$ofilename --header=$current_pwd/header.html

rm -rf $current_pwd/header.html
# copy setup file in working directory
cp $WRFexp $outputdir/${WRF_EXPID}.wrfexp
