categories:
- Climate Data Analysis
description: Shift longitudes ranging from 0. and 360 degrees to -180. and 180. degrees
homepage_url: https://github.com/NordicESMhub/galaxy-tools/blob/master/tools/shift-longitudes/shift_lon.py
long_description: |
  The wrapper aims at providing a simple utility to shift longitudes ranging from
  0. and 360 degrees to -180. and 180. degrees.
  The input file must be in netCDF format with geographical coordinates 
  (latitudes, longitudes) given in degrees.

name: shift-longitudes
owner: NordicESMHub
remote_repository_url: https://github.com/NordicESMhub/galaxy-tools/tree/master/tools/shift-longitudes
type: unrestricted
